---
title: "Formalise Model Pipeline on Spark Cluster"
output: html_notebook
---

```{r}
library(tidyverse)
library(sparklyr)
library(arrow)

config = spark_config()

config$`sparklyr.shell.driver-memory` <- "8G"
config$spark.memory.fraction <- 0.9

sc <- spark_connect(master = "local",config = config)
```

```{r}
train = readr::read_csv("../data/raw/train.csv")
test = readr::read_csv("../data/raw/test.csv")
```

```{r}
train_tbl = spark_read_csv(sc, name = "cover_type_train", path = "../data/raw/train.csv")
test_tbl = spark_read_csv(sc, name = "cover_type_test", path = "../data/raw/test.csv")
```

```{r}
train_tbl_enc <- 
  train_tbl %>% 
  mutate(Cover_Type = case_when(
    Cover_Type == 1 ~ "cover_type_1",
    Cover_Type == 2 ~ "cover_type_2",
    Cover_Type == 3 ~ "cover_type_3",
    Cover_Type == 4 ~ "cover_type_4",
    Cover_Type == 5 ~ "cover_type_5",
    Cover_Type == 6 ~ "cover_type_6",
    Cover_Type == 7 ~ "cover_type_7"
  ))

test_tbl_enc <- 
  test_tbl %>% 
  mutate(Cover_Type = case_when(
    Cover_Type == 1 ~ "cover_type_1",
    Cover_Type == 2 ~ "cover_type_2",
    Cover_Type == 3 ~ "cover_type_3",
    Cover_Type == 4 ~ "cover_type_4",
    Cover_Type == 5 ~ "cover_type_5",
    Cover_Type == 6 ~ "cover_type_6",
    Cover_Type == 7 ~ "cover_type_7"
  ))

xgb_model <- xgboost_classifier(train_tbl_enc,
                                Cover_Type ~ .,
                                # num_class = 7,
                                # num_round = 50,
                                # max_depth = 4
                                )

xgb_model %>%
  ml_predict(test_tbl_enc) %>%
  select(Cover_Type, predicted_label, starts_with("probability_")) %>%
  glimpse()
```


```{r}
# pipeline = ml_pipeline(sc) %>% 
  
  
  # ft_normalizer(uid = "transf_normalizer_cover_type")
```

```{r}
library(sparkxgb)

# pipeline <- ml_pipeline(sc)
# %>% 
  # ft_string_indexer("Cover_Type", "label")

vector_assembler <- ft_vector_assembler(
  sc, 
  input_cols = setdiff(colnames(train_tbl), "Cover_Type"), 
  output_col = "features"
)

normalizer <- ft_normalizer(
  sc,
  input_cols = "features", 
  output_col = "features",
  uid = "transf_normalizer_cover_type"
  )

xgb = xgboost_classifier(sc,objective = "multi:softmax", num_class = 7)
# logistic_regression <- ml_logistic_regression(sc)

# # obtain the labels from the fitted StringIndexerModel
# labels <- pipeline_model %>%
#   ml_stage("string_indexer") %>%
#   ml_labels()

# # IndexToString will convert the predicted numeric values back to class labels
# index_to_string <- ft_index_to_string(sc, "prediction", "predicted_label", 
#                                       labels = labels)

# construct a pipeline with these stages
prediction_pipeline <- ml_pipeline(
  sc,
  vector_assembler, 
  normalizer,
  xgb
)

pipeline <- ml_pipeline(sc) %>% 
  ft_vector_assembler(
  sc, 
  input_cols = setdiff(colnames(train_tbl), "Cover_Type"), 
  output_col = "features",
  uid = "assembler"
) %>% 
  ft_normalizer(
  sc,
  input_cols = "features", 
  output_col = "features",
  uid = "transf_normalizer_cover_type"
  ) 

# %>%
#   xgboost_classifier(sc,objective = "multi:softmax", num_class = 7,uid = "xgb")

# fit to data and make some predictions
prediction_model <- prediction_pipeline %>%
  ml_fit(iris_data$train)
predictions <- prediction_model %>%
  ml_transform(iris_data$validation)
predictions %>%
  select(Species, label:predicted_label) %>%
  glimpse()
```

```{r}
# pipeline <- ml_pipeline(sc) %>% 

step_1 <- 
train_tbl %>% 
  ft_vector_assembler(
    input_cols = setdiff(colnames(train_tbl), "Cover_Type"), 
    output_col = "features",
    uid = "assembler"
) 

step_1

step_1 %>% 
  ft_normalizer(
  input_cols = "features", 
  output_col = "features_norm",
  uid = "transf_normalizer_cover_type"
  ) 

# %>%
#   xgboost_classifier(sc,objective = "multi:softmax", num_class = 7,uid = "xgb")


# ft_vector_assembler(train_tbl, input_cols=setdiff(colnames(train_tbl), "Cover_Type"), output_col="features") %>%
#   ft_normalizer(input.col = "features", output.col = "features_norm")
```

```{r}
pipeline <- ml_pipeline(sc) %>%
  ft_vector_assembler(setdiff(colnames(train_tbl), "Cover_Type"), "features") %>%
  ml_gbt_regressor(label_col = "Cover_Type")


pipeline_model <- ml_fit(pipeline, train_tbl)
```

```{r}
pipeline_model
```

```{r}
pipeline_model %>% ml_predict(test_tbl)
```

```{r}
label_encoder <- 
  train_tbl %>% 
  mutate(Cover_Type = case_when(
    Cover_Type == 1 ~ "cover_type_1",
    Cover_Type == 2 ~ "cover_type_2",
    Cover_Type == 3 ~ "cover_type_3",
    Cover_Type == 4 ~ "cover_type_4",
    Cover_Type == 5 ~ "cover_type_5",
    Cover_Type == 6 ~ "cover_type_6",
    Cover_Type == 7 ~ "cover_type_7"
  ))
```

```{r}
pipeline_classification <- ml_pipeline(sc) %>%
  ft_dplyr_transformer(label_encoder) %>%
  ft_vector_assembler(setdiff(colnames(train_tbl), "Cover_Type"), "features") %>%
  ft_string_indexer("Cover_Type", "label",uid = "string_indexer") %>% 
  ml_gbt_classifier(label_col = "label")

classification_pipeline_model <- ml_fit(pipeline_classification, train_tbl)
```

```{r}
classification_pipeline_model %>% 
  ml_transform(test_tbl) %>%
  glimpse()
```
```{r}
labels <- classification_pipeline_model %>%
  ml_stage("string_indexer") %>%
  ml_labels()

```

```{r}
classification_pipeline_model
```

